const { jsPDF } = window.jspdf;
const SETTINGS_KEY = "factures-proba-settings-v1";
const CLIENTS_KEY = "factures-proba-clients-v1";
const SELECTED_KEY = "factures-proba-selected-v1";
const IPC_API = "https://servicios.ine.es/wstempus/js/ES/DATOS_SERIE/IPC251856?nult=120";
const MAKE_WEBHOOK = "https://hook.eu2.make.com/4cb928qynyqb02hhip1ou61ur6yispsc";
const baseline = {year:2026, month:10};
const DEFAULT_CLIENTS = [
  {key:"nineA",short:"Local 9A",company:"TELIEMPORDA, SL",tax:"B17549924",address:"C. Alba 3, local 9A",city:"17230 Palamós",base:1167.19,supplierTax:"E55317424",tel:"619930903",concept:"Lloguer del local 9A, situat al carrer Alba, 3 de Palamós",prefix:"C",startNumber:19},
  {key:"nineB",short:"Local 9B",company:"ACTIVIDADES DE RESTAURACIÓN Y OCIO NOCTURNO, SL",tax:"B56225733",address:"Carrer Alba, 3, local B",city:"17230 Palamós",base:889.50,supplierTax:"E55317424",tel:"619930903",concept:"Lloguer del local 9B, situat al carrer Alba, 3 de Palamós",prefix:"C",startNumber:20},
  {key:"A",short:"Av. Llibertat 3",company:"Gemma Calvet Farràs",tax:"40531002B",address:"Casa Pedralta, Paratge Bujonis, S/n",city:"17220 Sant Feliu de Guíxols",base:549.55,supplierTax:"E02723773",concept:"Lloguer del local situat a l'av. Llibertat, 3 de Palamós",prefix:"A",startNumber:11,own:true}
];
let clients = JSON.parse(localStorage.getItem(CLIENTS_KEY)||"null") || DEFAULT_CLIENTS;
clients = clients.map((c,i)=>({...DEFAULT_CLIENTS[i]||{},...c,prefix:c.prefix||((c.key==="A")?"A":"C"),startNumber:Number.isFinite(c.startNumber)?c.startNumber:(c.key==="A"?11:19+i)}));
let settings = JSON.parse(localStorage.getItem(SETTINGS_KEY)||"null") || {};
clients.forEach(c=>{settings[c.key] ||= {price:c.base,ipc:0,totalOverride:null};});
let selected = new Set(JSON.parse(localStorage.getItem(SELECTED_KEY)||"null") || clients.map(c=>c.key));
let attachments=[],draftIpc={},pendingIpc=null,ipcData=[];
const $=id=>document.getElementById(id);
const money=n=>new Intl.NumberFormat("ca-ES",{style:"currency",currency:"EUR"}).format(n);
const monthLabel=v=>new Intl.DateTimeFormat("ca-ES",{month:"long",year:"numeric"}).format(new Date(`${v}-01`));
const esc=s=>String(s??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[ch]));
function saveClients(){localStorage.setItem(CLIENTS_KEY,JSON.stringify(clients));}
function saveSettings(){localStorage.setItem(SETTINGS_KEY,JSON.stringify(settings));}
function monthData(){const[y,m]=($('period').value||"2026-10").split("-").map(Number);return{year:y,month:m};}
function ipcRecord(year,month){return ipcData.find(item=>item.Anyo===year&&item.FK_Periodo===month&&!item.Secreto)}
function latestIpcRecord(){return [...ipcData].filter(item=>!item.Secreto).sort((a,b)=>b.Fecha-a.Fecha)[0]}
function updateGeneralIpc(){const target=monthData(),record=ipcRecord(target.year,target.month),latest=latestIpcRecord(),value=$("general-ipc-value"),copy=$("general-ipc-copy"),status=$("general-ipc-status"),box=value.parentElement;if(record){value.textContent=`${record.Valor.toLocaleString("ca-ES",{minimumFractionDigits:1,maximumFractionDigits:1})} %`;copy.textContent=`Taxa anual oficial de l’IPC general per a ${monthLabel($("period").value)}.`;status.textContent="Dada publicada per l’INE";box.className="ipc-reference-value";return}value.textContent="No publicada";copy.textContent=latest?`L’INE encara no ha publicat la dada de ${monthLabel($("period").value)}.`:"No s’ha pogut consultar la dada oficial ara mateix.";status.textContent=latest?`Última dada: ${monthLabel(`${latest.Anyo}-${String(latest.FK_Periodo).padStart(2,"0")}`)} · ${latest.Valor.toLocaleString("ca-ES",{minimumFractionDigits:1,maximumFractionDigits:1})} %`:"Torna-ho a provar més tard";box.className="ipc-reference-value is-pending"}
async function loadGeneralIpc(){try{const response=await fetch(IPC_API);if(!response.ok)throw new Error("INE unavailable");const payload=await response.json();ipcData=payload.Data||[];updateGeneralIpc()}catch(error){ipcData=[];$("general-ipc-value").textContent="No disponible";$("general-ipc-copy").textContent="No s’ha pogut consultar l’INE ara mateix.";$("general-ipc-status").textContent="Font oficial no disponible";$("general-ipc-value").parentElement.className="ipc-reference-value is-error"}}
function numberFor(c){const d=monthData(),delta=(d.year-baseline.year)*12+d.month-baseline.month;return `${c.prefix||"C"}${d.year}-${String((c.startNumber||1)+delta).padStart(5,"0")}`;}
function current(c){const s=settings[c.key]||{price:c.base},price=Number.isFinite(s.price)?s.price:c.base,ipc=draftIpc[c.key]??0;return +(price*(1+ipc/100)).toFixed(2);}
function calculatedTotal(base){return +(base+round(base*.21)-round(base*.19)).toFixed(2)}
function invoiceTotal(c){const v=settings[c.key]?.totalOverride;return Number.isFinite(v)&&v!==null?+v.toFixed(2):calculatedTotal(current(c));}
function round(n){return Math.round((n+Number.EPSILON)*100)/100}
function render(){
  $("clients").innerHTML=clients.map(c=>`<article class="client-card"><div class="client-top"><h3>${esc(c.short)}</h3><label class="client-check"><input data-select="${esc(c.key)}" type="checkbox" ${selected.has(c.key)?"checked":""}> Incloure</label></div><div class="address">${esc(c.company)}<br>${esc(c.address)}<br>${esc(c.city)}</div><div class="invoice-no">${numberFor(c)}</div><div class="fields"><label>Preu base<input data-key="${esc(c.key)}" data-field="price" type="number" min="0" step="0.01" value="${(settings[c.key]?.price??c.base).toFixed(2)}"></label><label>IPC d’aquest període (%)<input data-key="${esc(c.key)}" data-field="ipc" type="number" step="0.1" value="${draftIpc[c.key]??0}"><button data-ipc-apply="${esc(c.key)}" class="button secondary" type="button">Aplicar IPC</button></label><label class="total-field">Total factura <small>(editable)</small><input data-key="${esc(c.key)}" data-field="totalOverride" type="number" min="0" step="0.01" value="${invoiceTotal(c).toFixed(2)}"></label></div><div class="amounts"><span>Base imposable<br><strong>${money(current(c))}</strong></span><span style="text-align:right">Total<br><strong>${money(invoiceTotal(c))}</strong></span></div><button class="client-edit" data-edit-client="${esc(c.key)}" type="button">Editar dades fiscals</button></article>`).join("");
  $("summary").textContent=`${selected.size} de ${clients.length} factures preparades per a ${monthLabel($("period").value)}`;
  document.querySelectorAll("input[data-key]").forEach(i=>i.addEventListener("change",()=>{const key=i.dataset.key;if(i.dataset.field==="ipc")draftIpc[key]=Number(i.value)||0;else{settings[key][i.dataset.field]=i.value.trim()===""?null:(Number(i.value)||0);saveSettings();}render();}));
  document.querySelectorAll("input[data-select]").forEach(i=>i.addEventListener("change",()=>{i.checked?selected.add(i.dataset.select):selected.delete(i.dataset.select);localStorage.setItem(SELECTED_KEY,JSON.stringify([...selected]));render();}));
  document.querySelectorAll("[data-ipc-apply]").forEach(b=>b.addEventListener("click",()=>{const key=b.dataset.ipcApply,ipc=draftIpc[key]||0;if(!ipc){alert("Introdueix primer un percentatge d’IPC.");return}pendingIpc={key,ipc};$("ipc-copy").textContent=`Has aplicat un IPC del ${ipc} % al ${clients.find(c=>c.key===key).short}.`;$("ipc-modal").classList.remove("hidden");}));
  document.querySelectorAll("[data-edit-client]").forEach(b=>b.addEventListener("click",()=>openClientForm(b.dataset.editClient)));
  $("attachment-list").innerHTML=attachments.map((a,i)=>`<div class="attachment-item"><span class="attachment-name">${esc(a.name)} <small>(${a.size<1024?`${a.size} B`:`${(a.size/1024).toFixed(1)} KB`})</small></span><button class="attachment-remove" data-attachment="${i}" type="button">Eliminar</button></div>`).join("");
  document.querySelectorAll("[data-attachment]").forEach(b=>b.addEventListener("click",()=>{attachments.splice(Number(b.dataset.attachment),1);render();}));
}
function reset(){settings=Object.fromEntries(clients.map(c=>[c.key,{price:c.base,ipc:0,totalOverride:null}]));draftIpc={};saveSettings();render();}
function closeIpc(){$("ipc-modal").classList.add("hidden");pendingIpc=null}
function applyIpcCurrent(){closeIpc();render()}
function fixIpc(){if(!pendingIpc)return;const{key,ipc}=pendingIpc;settings[key].price=+(settings[key].price*(1+ipc/100)).toFixed(2);settings[key].ipc=0;draftIpc[key]=0;saveSettings();closeIpc();render()}
function openClientForm(key){const c=clients.find(x=>x.key===key),isNew=!c;$("client-title").textContent=isNew?"Afegir client":"Editar dades fiscals";$("client-key").value=c?.key||"";$("client-short").value=c?.short||"";$("client-company").value=c?.company||"";$("client-tax").value=c?.tax||"";$("client-address").value=c?.address||"";$("client-city").value=c?.city||"";$("client-tel").value=c?.tel||"";$("client-email").value=c?.email||"";$("client-concept").value=c?.concept||"Lloguer del local";$("client-prefix").value=c?.prefix||"C";$("client-start").value=c?.startNumber||Math.max(...clients.filter(x=>(x.prefix||"C")===(c?.prefix||"C")).map(x=>x.startNumber||0),0)+1;$("client-price").value=settings[c?.key]?.price??c?.base??0;$("client-modal").classList.remove("hidden")}
function closeClientForm(){$("client-modal").classList.add("hidden")}
function saveClientForm(e){e.preventDefault();const key=$("client-key").value||`client-${Date.now()}`,old=clients.find(c=>c.key===key),data={key,short:$("client-short").value.trim(),company:$("client-company").value.trim(),tax:$("client-tax").value.trim(),address:$("client-address").value.trim(),city:$("client-city").value.trim(),tel:$("client-tel").value.trim(),email:$("client-email").value.trim(),concept:$("client-concept").value.trim(),prefix:$("client-prefix").value.trim().toUpperCase()||"C",startNumber:Number($("client-start").value)||1,base:Number($("client-price").value)||0,supplierTax:old?.supplierTax||"E55317424",own:old?.own||false};if(old)Object.assign(old,data);else{clients.push(data);selected.add(key)}settings[key] ||= {price:data.base,ipc:0,totalOverride:null};settings[key].price=Number($("client-price").value)||0;saveClients();saveSettings();localStorage.setItem(SELECTED_KEY,JSON.stringify([...selected]));closeClientForm();render()}
function openReview(){const d=monthData(),chosen=clients.filter(c=>selected.has(c.key));if(!chosen.length){alert("Selecciona almenys una factura.");return}$("review-copy").textContent=`Es generaran ${chosen.length} factura${chosen.length===1?"":"es"} amb data 01/${String(d.month).padStart(2,"0")}/${d.year}.`;$("review-list").innerHTML=chosen.map(c=>`<li><span>${esc(c.short)}</span><strong>${numberFor(c)} · ${money(invoiceTotal(c))}</strong></li>`).join("");$("confirm").textContent=`Descarregar ${chosen.length===1?"la factura":"les factures seleccionades"}`;$("review").classList.remove("hidden")}
function closeReview(){$("review").classList.add("hidden")}
function addText(c,s,x,y,size=10,bold=false){c.setFont("helvetica",bold?"bold":"normal");c.setFontSize(size);c.text(s,x,y)}
function rightText(c,s,x,y,size=10,bold=false){c.setFont("helvetica",bold?"bold":"normal");c.setFontSize(size);c.text(s,x,y,{align:"right"})}
function addFit(c,s,x,y,maxWidth,size=10,bold=false){let n=size;c.setFont("helvetica",bold?"bold":"normal");c.setFontSize(n);while(n>8&&c.getTextWidth(s)>maxWidth){n-=.25;c.setFontSize(n)}c.text(s,x,y)}
function pdfFor(client){const d=monthData(),base=current(client),iva=round(base*.21),irpf=round(base*.19),grand=invoiceTotal(client),doc=new jsPDF({unit:"pt",format:"a4"}),W=595.28,L=34,R=34,HX=296,HR=W-R;doc.setTextColor(0);doc.setFillColor(217,217,217);doc.rect(HX,54,HR-HX,23,"F");addText(doc,"FACTURA",HX+3,70,13,true);rightText(doc,numberFor(client),HR-3,70,13,true);addText(doc,"Data",HX+3,94,11);rightText(doc,`01/${String(d.month).padStart(2,"0")}/${d.year}`,HR-3,94,11);addText(doc,client.own?"BERNABEU OLIVER CB":"BERNABEU-BASSETS CB",L,160,10,true);addFit(doc,client.company,HX+3,160,HR-HX-6,10,true);addText(doc,client.supplierTax,L,178,10,true);addText(doc,client.tax,HX+3,178,10,true);addText(doc,"Av. Llibertat, 1",L,196);addText(doc,client.address,HX+3,196);addText(doc,"17230 Palamós",L,214);addText(doc,client.city,HX+3,214);if(client.tel)addText(doc,`Telf.: ${client.tel}`,L,232);const month=new Intl.DateTimeFormat("ca-ES",{month:"long"}).format(new Date(d.year,d.month-1));doc.setFillColor(217,217,217);doc.rect(L,223,W-L-R,24,"F");addText(doc,"Concepte",L+4,239,10,true);doc.text("IVA",411,239,{align:"center"});rightText(doc,"Import",HR-7,239,10,true);doc.setLineWidth(2);doc.line(L,247,HR,247);addFit(doc,`${client.concept}, ${month.toUpperCase()}`,L+4,261,315,10);addText(doc,`${d.year}.`,L+4,279);doc.text("21 %",411,261,{align:"center"});rightText(doc,money(base),HR-7,261);rightText(doc,"Base Imposable",493,332);rightText(doc,money(base),HR-7,332);rightText(doc,"IVA 21 %",493,350);rightText(doc,money(iva),HR-7,350);rightText(doc,"Retenció IRPF 19 %",493,368);rightText(doc,`-${money(irpf)}`,HR-7,368);doc.setFillColor(238,238,238);doc.rect(HX+26,374,HR-(HX+26),20,"F");doc.setFillColor(0);doc.setFont("helvetica","bold");doc.setFontSize(10);doc.text("Total",430,389);const totalText=money(grand);doc.text(totalText,HR-7-doc.getTextWidth(totalText),389);addText(doc,"Podeu fer l'ingrés al compte bancari:",L+4,770);addText(doc,`IBAN: ES8721000028710200787236`,L+17,786);doc.text("Pàgina 1 / 1",W/2,817,{align:"center"});return doc}
function invoicePayload(client){const pdf=pdfFor(client),fileName=`FACTURA ${monthLabel($("period").value).toUpperCase()} - ${client.short.toUpperCase()}.pdf`,dataUri=pdf.output("datauristring");return{month:monthLabel($("period").value),year:monthData().year,invoiceNumber:numberFor(client),clientKey:client.key,clientName:client.company,clientEmail:client.email||"",fileName,pdfBase64:dataUri.split(",")[1]||"",total:invoiceTotal(client),test:false}}
function downloadAll(){clients.filter(c=>selected.has(c.key)).forEach(c=>pdfFor(c).save(`FACTURA ${monthLabel($("period").value).toUpperCase()} - ${c.short.toUpperCase()}.pdf`));closeReview()}
async function sendToMake(){const chosen=clients.filter(c=>selected.has(c.key));if(!chosen.length){alert("Selecciona almenys una factura.");return}const withoutEmail=chosen.filter(c=>!c.email);if(withoutEmail.length&&!confirm(`Falten els correus de ${withoutEmail.map(c=>c.short).join(", ")}. Vols continuar igualment?`))return;const button=$("send-automation");button.disabled=true;button.textContent="Preparant...";try{for(const client of chosen){const response=await fetch(MAKE_WEBHOOK,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(invoicePayload(client))});if(!response.ok)throw new Error(`Make ha respost amb ${response.status}`)}alert(`S’han preparat ${chosen.length} factura${chosen.length===1?"":"es"}: s’han desat al Drive i s’han creat els esborranys de Gmail.`);closeReview()}catch(error){alert(`No s’ha pogut completar la preparació: ${error.message}`)}finally{button.disabled=false;button.textContent="Guardar al Drive i preparar correu"}}
$("comments").value=localStorage.getItem("factures-proba-comments-v1")||"";$("comments").addEventListener("input",()=>localStorage.setItem("factures-proba-comments-v1",$("comments").value));$("attachments").addEventListener("change",e=>{attachments.push(...Array.from(e.target.files));e.target.value="";render()});$("period").addEventListener("change",()=>{draftIpc={};render()});$("reset").addEventListener("click",reset);$("add-client").addEventListener("click",()=>openClientForm());$("client-form").addEventListener("submit",saveClientForm);$("cancel-client").addEventListener("click",closeClientForm);$("close-client").addEventListener("click",closeClientForm);$("download-selected").addEventListener("click",openReview);$("download-all").addEventListener("click",()=>{selected=new Set(clients.map(c=>c.key));localStorage.setItem(SELECTED_KEY,JSON.stringify([...selected]));render();openReview()});$("confirm").addEventListener("click",downloadAll);$("cancel").addEventListener("click",closeReview);$("close-review").addEventListener("click",closeReview);$("ipc-current").addEventListener("click",applyIpcCurrent);$("ipc-fix").addEventListener("click",fixIpc);$("close-ipc").addEventListener("click",closeIpc);render();
$("send-automation").addEventListener("click",sendToMake);
loadGeneralIpc();
$("period").addEventListener("change",updateGeneralIpc);
