const CLIENTS_KEY="factures-proba-clients-v1",SETTINGS_KEY="factures-proba-settings-v1";
const $=id=>document.getElementById(id),money=n=>new Intl.NumberFormat("ca-ES",{style:"currency",currency:"EUR"}).format(n),esc=s=>String(s??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#039;"}[ch]));
const defaults=[{key:"nineA",short:"Local 9A",company:"TELIEMPORDA, SL",email:""},{key:"nineB",short:"Local 9B",company:"ACTIVIDADES DE RESTAURACIÓN Y OCIO NOCTURNO, SL",email:""},{key:"A",short:"Av. Llibertat 3",company:"Gemma Calvet Farràs",email:""}];
let clients=JSON.parse(localStorage.getItem(CLIENTS_KEY)||"null")||defaults,settings=JSON.parse(localStorage.getItem(SETTINGS_KEY)||"null")||{};
function period(){const [y,m]=($("email-period").value||"2026-10").split("-").map(Number);return{year:y,month:m}}
function month(){return new Intl.DateTimeFormat("ca-ES",{month:"long",year:"numeric"}).format(new Date(`${$("email-period").value}-01`))}
function numberFor(c){const d=period(),delta=(d.year-2026)*12+d.month-10;return `${c.prefix||"C"}${d.year}-${String((c.startNumber||1)+delta).padStart(5,"0")}`}
function total(c){const v=settings[c.key]?.totalOverride,price=Number(settings[c.key]?.price??c.base??0);return Number.isFinite(v)?v:+(price+price*.21-price*.19).toFixed(2)}
function template(value,c){const d=period(),m=month(),replacements={"{client}":c.company||c.short,"{mes}":m,"{numero}":numberFor(c),"{total}":money(total(c))};return Object.entries(replacements).reduce((text,[from,to])=>text.split(from).join(to),value)}
function saveEmail(key,email){const c=clients.find(x=>x.key===key);if(c){c.email=email;localStorage.setItem(CLIENTS_KEY,JSON.stringify(clients))}}
function compose(c){const email=c.email?.trim();if(!email){alert("Afegeix primer el correu del client.");return}const subject=template($("email-subject").value,c),body=template($("email-body").value,c),url=`https://mail.google.com/mail/?view=cm&fs=1&to=${encodeURIComponent(email)}&su=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;window.open(url,"_blank","noopener")}
function render(){const box=$("email-clients");box.innerHTML=clients.map(c=>`<article class="email-client"><div><h3>${esc(c.short)}</h3><p>${esc(c.company||"")} · ${esc(numberFor(c))} · ${money(total(c))}</p></div><div class="email-client-actions"><input data-email-key="${esc(c.key)}" type="email" placeholder="correu del client" value="${esc(c.email||"")}"><button class="button primary" data-compose="${esc(c.key)}" type="button">Obrir Gmail</button></div></article>`).join("");document.querySelectorAll("[data-email-key]").forEach(input=>input.addEventListener("change",()=>saveEmail(input.dataset.emailKey,input.value)));document.querySelectorAll("[data-compose]").forEach(button=>button.addEventListener("click",()=>compose(clients.find(c=>c.key===button.dataset.compose))));}
$("email-period").addEventListener("change",render);render();
